[diff]
#    command = "meld"
#    args = ["--diff", "{{ .Destination }}", "{{ .Target }}"]
    pager = "diff-so-fancy"
[[textconv]]
pattern = "**/*.plist"
command = "plutil"
args = ["-convert", "xml1", "-o", "-", "-"]

[scriptEnv]
    GITHUB_USERNAME = "uhop"
